[package]
name = "u5-gic-timer"
version = "0.1.0"
edition = "2021"

[lib]
name = "u5_gic_timer"
path = "src/lib.rs"

[dependencies]
pathn-contracts = { path = "../../contracts" }

[dev-dependencies]
u17-virtio-blk = { path = "../u17-virtio-blk" }
u18-virtio-console = { path = "../u18-virtio-console" }
u6-virtio-transport = { path = "../u6-virtio-transport" }
