//! # aidl_compat
//!
//! AOSP AIDL Interface Integration and Rust Traits Compatibility Crate for AndroidWebGPU.
//! Provides traits, types, macros, and smart pointer wrappers enabling code generated by
//! official AOSP `aidl --lang=rust` to build and execute cleanly.

pub mod death;
pub mod holder;
pub mod macros;
pub mod pointer;
pub mod proxy;
pub mod status;
pub mod stub;
pub mod traits;

// -----------------------------------------------------------------------------
// Top-Level Public Exports (AOSP `binder::*` namespace surface)
// -----------------------------------------------------------------------------

pub use death::{DeathCallback, DeathRecipient, DeathRecipientRegistry};
pub use holder::{ParcelFileDescriptor, ParcelableHolder};
pub use pointer::{SpIBinder, Strong, WpIBinder};
pub use proxy::{transact_sync, BpInterface};
pub use status::{
    Exception, ExceptionCode, Result, ServiceSpecificException, Status, StatusCode,
    EX_BAD_PARCELABLE, EX_HAS_REPLY_HEADER, EX_ILLEGAL_ARGUMENT, EX_ILLEGAL_STATE,
    EX_NETWORK_MAIN_THREAD, EX_NONE, EX_NULL_POINTER, EX_PARCELABLE, EX_SECURITY,
    EX_SERVICE_SPECIFIC, EX_TRANSACTION_FAILED, EX_UNSUPPORTED_OPERATION, STATUS_ALREADY_EXISTS,
    STATUS_BAD_TYPE, STATUS_BAD_VALUE, STATUS_DEAD_OBJECT, STATUS_FAILED_TRANSACTION,
    STATUS_INVALID_OPERATION, STATUS_NAME_NOT_FOUND, STATUS_NO_MEMORY, STATUS_OK,
    STATUS_PERMISSION_DENIED, STATUS_TIMED_OUT, STATUS_UNKNOWN_ERROR, STATUS_UNKNOWN_TRANSACTION,
};
pub use stub::{Binder, BinderFeatures, RemoteBinder, RemoteTransport};
pub use traits::{FromIBinder, IBinder, Interface, Parcelable, Proxy, Remotable};

// Direct re-exports from binder_rt runtime
pub use binder_rt::types::{
    BinderObjectHeader, BinderSizeT, BinderUintptrT, FlatBinderObject, TransactionCode,
    TransactionFlags, BINDER_TYPE_BINDER, BINDER_TYPE_FD, BINDER_TYPE_FDA, BINDER_TYPE_HANDLE,
    BINDER_TYPE_PTR, BINDER_TYPE_WEAK_BINDER, BINDER_TYPE_WEAK_HANDLE,
};
pub use binder_rt::wire::{
    BinderHandleCookie, BinderPtrCookie, BinderTransactionData, BC_ACQUIRE, BC_ACQUIRE_DONE,
    BC_ACQUIRE_RESULT, BC_ATTEMPT_ACQUIRE, BC_CLEAR_DEATH_NOTIFICATION, BC_DEAD_BINDER_DONE,
    BC_DECREFS, BC_ENTER_LOOPER, BC_EXIT_LOOPER, BC_FREE_BUFFER, BC_INCREFS, BC_INCREFS_DONE,
    BC_REGISTER_LOOPER, BC_RELEASE, BC_REPLY, BC_REQUEST_DEATH_NOTIFICATION, BC_TRANSACTION,
    BR_ACQUIRE, BR_ACQUIRE_RESULT, BR_CLEAR_DEATH_NOTIFICATION_DONE, BR_DEAD_BINDER, BR_DEAD_REPLY,
    BR_DECREFS, BR_ERROR, BR_FAILED_REPLY, BR_FINISHED, BR_INCREFS, BR_NOOP, BR_OK, BR_RELEASE,
    BR_REPLY, BR_SPAWN_LOOPER, BR_TRANSACTION, BR_TRANSACTION_COMPLETE, DUMP_TRANSACTION,
    FIRST_CALL_TRANSACTION, INTERFACE_TRANSACTION, LAST_CALL_TRANSACTION, PING_TRANSACTION,
    SHELL_CMD_TRANSACTION, SYSPROPS_TRANSACTION, TF_ACCEPT_FDS, TF_CLEAR_BUF, TF_ONE_WAY,
    TF_ROOT_OBJECT, TF_STATUS_CODE,
};
pub use binder_rt::{Parcel, ParcelError};

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Arc;

    #[test]
    fn test_sp_wp_lifecycle() {
        let dummy = RemoteBinder::new(10, 0x1234);
        assert_eq!(dummy.handle(), Some(10));
        assert!(dummy.is_binder_alive());

        let weak = dummy.downgrade();
        let strong = weak.upgrade().expect("Upgrade should succeed");
        assert_eq!(strong.handle(), Some(10));
    }

    #[test]
    fn test_death_recipient_lifecycle() {
        use std::sync::atomic::{AtomicUsize, Ordering};

        let death_count = Arc::new(AtomicUsize::new(0));
        let dc_clone = Arc::clone(&death_count);

        let recipient: Arc<dyn DeathRecipient> = Arc::new(DeathCallback(move || {
            dc_clone.fetch_add(1, Ordering::SeqCst);
        }));

        let registry = DeathRecipientRegistry::new();
        assert_eq!(registry.recipient_count(), 0);

        registry.link(Arc::clone(&recipient), true).unwrap();
        assert_eq!(registry.recipient_count(), 1);

        // Unlink
        registry.unlink(&recipient).unwrap();
        assert_eq!(registry.recipient_count(), 0);

        // Link again and trigger death
        registry.link(recipient, true).unwrap();
        registry.notify_death();
        assert_eq!(death_count.load(Ordering::SeqCst), 1);
        assert_eq!(registry.recipient_count(), 0);
    }
}
