[workspace]
resolver = "2"
members = [
    "crates/gles2wgpu",
    "crates/virtio_gpu_bridge",
    "crates/webgpu_compositor",
    "crates/webgpu_swapchain",
    "crates/apk_gpu_analyzer",
    "crates/binder_rt",
    "crates/aidl_compat",
    "crates/metrics_overlay",
    "crates/vulkan2wgpu",
    "crates/virtio_binder",
    "crates/binder_handle_bridge",
    "crates/binder_routing",
    "crates/binder_sys",
    "crates/surfaceflinger_gpu_service",
    "crates/pms_rs",
    "crates/zygote_client",
    "crates/ams_rs",
    "crates/tests_e2e_binder",
    "crates/input_channel",
    "crates/wms_rs",
    "crates/inputflinger_rs",
    "crates/sensors_hal_virtual",
    "crates/sensor_host_rs",
    "crates/audio_hal_virtual",
    "crates/audio_host_rs",
    "crates/vintf_validator",
    "crates/camera_hal_virtual",
    "crates/camera_host_rs",
    "crates/media_host_rs",
    "crates/tests_e2e_system_services",
]

[workspace.dependencies]
wgpu = "24.0"
naga = { version = "24.0", features = ["glsl-in", "spv-in", "wgsl-out"] }
bytemuck = { version = "1.21", features = ["derive"] }
pollster = "0.4"
thiserror = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1"
