//! Virtio-Binder wire protocol definitions and packet framing.
//!
//! Conforms to Virtio ID 44 (`VIRTIO_ID_BINDER`) and 64-bit Android Binder IPC C-ABI.

use binder_rt::types::BinderSizeT;
use binder_rt::wire::{BR_OK, BR_REPLY, BR_TRANSACTION_COMPLETE, PING_TRANSACTION, TF_ONE_WAY};
use binder_rt::Parcel;
use bytemuck::{Pod, Zeroable};
use thiserror::Error;

/// OASIS / Custom Virtio Device ID for Paravirtualized Binder.
pub const VIRTIO_ID_BINDER: u32 = 44;

/// Virtqueue index 0: Bidirectional Request / Reply Queue.
pub const VIRTIO_BINDER_QUEUE_TX_RX: u16 = 0;

/// Virtqueue index 1: Host-to-Guest Asynchronous Event / Death Notification Queue.
pub const VIRTIO_BINDER_QUEUE_EVENT: u16 = 1;

// -----------------------------------------------------------------------------
// Virtio-Binder Command Constants
// -----------------------------------------------------------------------------

/// Perform an IPC transaction against a target handle.
pub const CMD_TRANSACT: u32 = 1;

/// Increment strong reference count for a target handle.
pub const CMD_ACQUIRE: u32 = 2;

/// Decrement strong reference count for a target handle.
pub const CMD_RELEASE: u32 = 3;

/// Link death notification recipient to a target handle.
pub const CMD_LINK_DEATH: u32 = 4;

/// Unlink death notification recipient from a target handle.
pub const CMD_UNLINK_DEATH: u32 = 5;

/// Ping remote handle or host service manager.
pub const CMD_PING: u32 = 6;

// -----------------------------------------------------------------------------
// Virtio-Binder Event Type Constants
// -----------------------------------------------------------------------------

/// Death notification for a host service.
pub const EVENT_TYPE_DEATH: u32 = 1;

/// Acquire reference notification.
pub const EVENT_TYPE_ACQUIRE: u32 = 2;

/// Release reference notification.
pub const EVENT_TYPE_RELEASE: u32 = 3;

// -----------------------------------------------------------------------------
// Protocol Errors
// -----------------------------------------------------------------------------

/// Errors occurring during Virtio-Binder packet serialization or deserialization.
#[derive(Debug, Error, PartialEq, Eq, Clone)]
pub enum ProtocolError {
    #[error("Packet too short: expected at least {expected} bytes, found {actual}")]
    PacketTooShort { expected: usize, actual: usize },

    #[error("Payload size mismatch: data_size ({data_size}) + offsets_size ({offsets_size}) > remaining payload ({remaining})")]
    PayloadSizeMismatch {
        data_size: usize,
        offsets_size: usize,
        remaining: usize,
    },

    #[error("Offsets size {0} is not a multiple of sizeof(BinderSizeT) (8 bytes)")]
    InvalidOffsetsSize(usize),

    #[error("Unknown or invalid command opcode: {0}")]
    InvalidCommand(u32),

    #[error("Parcel conversion error: {0}")]
    ParcelConversionError(String),
}

// -----------------------------------------------------------------------------
// Request Header: VirtioBinderReqHdr
// -----------------------------------------------------------------------------

/// 48-byte 64-bit C-ABI Request Header for Virtio-Binder transactions.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Pod, Zeroable, Default)]
pub struct VirtioBinderReqHdr {
    /// Unique transaction sequence number generated by guest transport.
    pub msg_id: u64,
    /// Command opcode (`CMD_TRANSACT`, `CMD_ACQUIRE`, `CMD_RELEASE`, etc.).
    pub cmd: u32,
    /// Target Binder handle ID (0 for ServiceManager).
    pub target_handle: u32,
    /// AIDL Transaction code (e.g., 1, 2, `PING_TRANSACTION`).
    pub code: u32,
    /// Transaction flags (`TF_ONE_WAY`, etc.).
    pub flags: u32,
    /// Sender cookie / tracking token.
    pub cookie: u64,
    /// Length of following Parcel payload in bytes.
    pub data_size: u32,
    /// Length of offsets array in bytes (`count * 8`).
    pub offsets_size: u32,
    /// Alignment padding.
    pub padding: u32,
    /// Reserved field for 8-byte alignment.
    pub _reserved: u32,
}

impl VirtioBinderReqHdr {
    /// Construct a new transaction request header.
    #[allow(clippy::too_many_arguments)]
    pub const fn new_transact(
        msg_id: u64,
        target_handle: u32,
        code: u32,
        flags: u32,
        cookie: u64,
        data_size: u32,
        offsets_size: u32,
    ) -> Self {
        Self {
            msg_id,
            cmd: CMD_TRANSACT,
            target_handle,
            code,
            flags,
            cookie,
            data_size,
            offsets_size,
            padding: 0,
            _reserved: 0,
        }
    }

    /// Construct a new ping request header.
    pub const fn new_ping(msg_id: u64, target_handle: u32) -> Self {
        Self {
            msg_id,
            cmd: CMD_PING,
            target_handle,
            code: PING_TRANSACTION,
            flags: 0,
            cookie: 0,
            data_size: 0,
            offsets_size: 0,
            padding: 0,
            _reserved: 0,
        }
    }

    /// Construct a new acquire reference request header.
    pub const fn new_acquire(msg_id: u64, target_handle: u32) -> Self {
        Self {
            msg_id,
            cmd: CMD_ACQUIRE,
            target_handle,
            code: 0,
            flags: 0,
            cookie: 0,
            data_size: 0,
            offsets_size: 0,
            padding: 0,
            _reserved: 0,
        }
    }

    /// Construct a new release reference request header.
    pub const fn new_release(msg_id: u64, target_handle: u32) -> Self {
        Self {
            msg_id,
            cmd: CMD_RELEASE,
            target_handle,
            code: 0,
            flags: 0,
            cookie: 0,
            data_size: 0,
            offsets_size: 0,
            padding: 0,
            _reserved: 0,
        }
    }

    /// Construct a new link death request header.
    pub const fn new_link_death(msg_id: u64, target_handle: u32, cookie: u64) -> Self {
        Self {
            msg_id,
            cmd: CMD_LINK_DEATH,
            target_handle,
            code: 0,
            flags: 0,
            cookie,
            data_size: 0,
            offsets_size: 0,
            padding: 0,
            _reserved: 0,
        }
    }

    /// Construct a new unlink death request header.
    pub const fn new_unlink_death(msg_id: u64, target_handle: u32, cookie: u64) -> Self {
        Self {
            msg_id,
            cmd: CMD_UNLINK_DEATH,
            target_handle,
            code: 0,
            flags: 0,
            cookie,
            data_size: 0,
            offsets_size: 0,
            padding: 0,
            _reserved: 0,
        }
    }

    /// Return true if this is an asynchronous one-way transaction.
    pub const fn is_one_way(&self) -> bool {
        (self.flags & TF_ONE_WAY) != 0
    }

    /// Return raw byte slice representation.
    pub fn as_bytes(&self) -> &[u8] {
        bytemuck::bytes_of(self)
    }

    /// Parse header from byte slice.
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, ProtocolError> {
        let hdr_size = std::mem::size_of::<Self>();
        if bytes.len() < hdr_size {
            return Err(ProtocolError::PacketTooShort {
                expected: hdr_size,
                actual: bytes.len(),
            });
        }
        let mut hdr_bytes = [0u8; std::mem::size_of::<Self>()];
        hdr_bytes.copy_from_slice(&bytes[..hdr_size]);
        let hdr: Self = bytemuck::pod_read_unaligned(&hdr_bytes);
        Ok(hdr)
    }
}

// -----------------------------------------------------------------------------
// Response Header: VirtioBinderRespHdr
// -----------------------------------------------------------------------------

/// 32-byte 64-bit C-ABI Response Header for Virtio-Binder transactions.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Pod, Zeroable, Default)]
pub struct VirtioBinderRespHdr {
    /// Matching transaction sequence number.
    pub msg_id: u64,
    /// Binder kernel status code (0 = `STATUS_OK`, `<0` = error).
    pub status: i32,
    /// Return code (`BR_REPLY`, `BR_DEAD_REPLY`, `BR_TRANSACTION_COMPLETE`, `BR_FAILED_REPLY`).
    pub result_code: i32,
    /// Length of response Parcel payload in bytes.
    pub data_size: u32,
    /// Length of response offsets array in bytes.
    pub offsets_size: u32,
    /// Response flags.
    pub flags: u32,
    /// Alignment padding.
    pub padding: u32,
}

impl VirtioBinderRespHdr {
    /// Construct a new response header.
    pub const fn new(
        msg_id: u64,
        status: i32,
        result_code: i32,
        data_size: u32,
        offsets_size: u32,
        flags: u32,
    ) -> Self {
        Self {
            msg_id,
            status,
            result_code,
            data_size,
            offsets_size,
            flags,
            padding: 0,
        }
    }

    /// Construct a success response header (`STATUS_OK` / `BR_REPLY`).
    pub const fn new_ok(msg_id: u64, data_size: u32, offsets_size: u32) -> Self {
        Self::new(
            msg_id,
            binder_rt::status::STATUS_OK,
            BR_REPLY as i32,
            data_size,
            offsets_size,
            0,
        )
    }

    /// Construct an asynchronous completion response header (`BR_TRANSACTION_COMPLETE`).
    pub const fn new_one_way_complete(msg_id: u64) -> Self {
        Self::new(
            msg_id,
            binder_rt::status::STATUS_OK,
            BR_TRANSACTION_COMPLETE as i32,
            0,
            0,
            0,
        )
    }

    /// Construct an error response header.
    pub const fn new_error(msg_id: u64, status: i32, result_code: i32) -> Self {
        Self::new(msg_id, status, result_code, 0, 0, 0)
    }

    /// Return true if the transaction succeeded.
    pub const fn is_success(&self) -> bool {
        self.status == binder_rt::status::STATUS_OK
            && (self.result_code == BR_REPLY as i32
                || self.result_code == BR_TRANSACTION_COMPLETE as i32
                || self.result_code == BR_OK as i32)
    }

    /// Return raw byte slice representation.
    pub fn as_bytes(&self) -> &[u8] {
        bytemuck::bytes_of(self)
    }

    /// Parse header from byte slice.
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, ProtocolError> {
        let hdr_size = std::mem::size_of::<Self>();
        if bytes.len() < hdr_size {
            return Err(ProtocolError::PacketTooShort {
                expected: hdr_size,
                actual: bytes.len(),
            });
        }
        let mut hdr_bytes = [0u8; std::mem::size_of::<Self>()];
        hdr_bytes.copy_from_slice(&bytes[..hdr_size]);
        let hdr: Self = bytemuck::pod_read_unaligned(&hdr_bytes);
        Ok(hdr)
    }
}

// -----------------------------------------------------------------------------
// Event Header: VirtioBinderEventHdr
// -----------------------------------------------------------------------------

/// 16-byte C-ABI Event Header for asynchronous Queue 1 notifications.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Pod, Zeroable, Default)]
pub struct VirtioBinderEventHdr {
    /// Event type (`EVENT_TYPE_DEATH`, `EVENT_TYPE_ACQUIRE`, `EVENT_TYPE_RELEASE`).
    pub event_type: u32,
    /// Target handle ID associated with event.
    pub target_handle: u32,
    /// Registered death recipient cookie.
    pub cookie: u64,
}

impl VirtioBinderEventHdr {
    /// Construct a death notification event.
    pub const fn new_death(target_handle: u32, cookie: u64) -> Self {
        Self {
            event_type: EVENT_TYPE_DEATH,
            target_handle,
            cookie,
        }
    }

    /// Construct an acquire reference event.
    pub const fn new_acquire(target_handle: u32, cookie: u64) -> Self {
        Self {
            event_type: EVENT_TYPE_ACQUIRE,
            target_handle,
            cookie,
        }
    }

    /// Construct a release reference event.
    pub const fn new_release(target_handle: u32, cookie: u64) -> Self {
        Self {
            event_type: EVENT_TYPE_RELEASE,
            target_handle,
            cookie,
        }
    }

    /// Return raw byte slice representation.
    pub fn as_bytes(&self) -> &[u8] {
        bytemuck::bytes_of(self)
    }

    /// Parse header from byte slice.
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, ProtocolError> {
        let hdr_size = std::mem::size_of::<Self>();
        if bytes.len() < hdr_size {
            return Err(ProtocolError::PacketTooShort {
                expected: hdr_size,
                actual: bytes.len(),
            });
        }
        let mut hdr_bytes = [0u8; std::mem::size_of::<Self>()];
        hdr_bytes.copy_from_slice(&bytes[..hdr_size]);
        let hdr: Self = bytemuck::pod_read_unaligned(&hdr_bytes);
        Ok(hdr)
    }
}

// -----------------------------------------------------------------------------
// Framed Packet Structures
// -----------------------------------------------------------------------------

/// Fully framed request packet containing header, parcel data bytes, and offsets array.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VirtioBinderRequest {
    pub hdr: VirtioBinderReqHdr,
    pub data: Vec<u8>,
    pub offsets: Vec<BinderSizeT>,
}

impl VirtioBinderRequest {
    /// Create a new transaction request with given payload data and offsets.
    pub fn new_transact(
        msg_id: u64,
        target_handle: u32,
        code: u32,
        flags: u32,
        cookie: u64,
        data: Vec<u8>,
        offsets: Vec<BinderSizeT>,
    ) -> Self {
        let data_size = data.len() as u32;
        let offsets_size = (offsets.len() * std::mem::size_of::<BinderSizeT>()) as u32;
        let hdr = VirtioBinderReqHdr::new_transact(
            msg_id,
            target_handle,
            code,
            flags,
            cookie,
            data_size,
            offsets_size,
        );
        Self { hdr, data, offsets }
    }

    /// Create a request packet from an existing `Parcel`.
    pub fn from_parcel(
        msg_id: u64,
        target_handle: u32,
        code: u32,
        flags: u32,
        cookie: u64,
        parcel: &Parcel,
    ) -> Self {
        let data = parcel.data().to_vec();
        let offsets = parcel.offsets().to_vec();
        Self::new_transact(
            msg_id,
            target_handle,
            code,
            flags,
            cookie,
            data,
            offsets,
        )
    }

    /// Create a ping request packet.
    pub fn new_ping(msg_id: u64, target_handle: u32) -> Self {
        Self {
            hdr: VirtioBinderReqHdr::new_ping(msg_id, target_handle),
            data: Vec::new(),
            offsets: Vec::new(),
        }
    }

    /// Create an acquire request packet.
    pub fn new_acquire(msg_id: u64, target_handle: u32) -> Self {
        Self {
            hdr: VirtioBinderReqHdr::new_acquire(msg_id, target_handle),
            data: Vec::new(),
            offsets: Vec::new(),
        }
    }

    /// Create a release request packet.
    pub fn new_release(msg_id: u64, target_handle: u32) -> Self {
        Self {
            hdr: VirtioBinderReqHdr::new_release(msg_id, target_handle),
            data: Vec::new(),
            offsets: Vec::new(),
        }
    }

    /// Create a link death request packet.
    pub fn new_link_death(msg_id: u64, target_handle: u32, cookie: u64) -> Self {
        Self {
            hdr: VirtioBinderReqHdr::new_link_death(msg_id, target_handle, cookie),
            data: Vec::new(),
            offsets: Vec::new(),
        }
    }

    /// Create an unlink death request packet.
    pub fn new_unlink_death(msg_id: u64, target_handle: u32, cookie: u64) -> Self {
        Self {
            hdr: VirtioBinderReqHdr::new_unlink_death(msg_id, target_handle, cookie),
            data: Vec::new(),
            offsets: Vec::new(),
        }
    }

    /// Serialize entire request into contiguous byte vector.
    pub fn serialize(&self) -> Vec<u8> {
        let hdr_bytes = self.hdr.as_bytes();
        let offsets_bytes: &[u8] = bytemuck::cast_slice(&self.offsets);
        let mut out = Vec::with_capacity(hdr_bytes.len() + self.data.len() + offsets_bytes.len());
        out.extend_from_slice(hdr_bytes);
        out.extend_from_slice(&self.data);
        out.extend_from_slice(offsets_bytes);
        out
    }

    /// Deserialize a request packet from a byte slice.
    pub fn deserialize(bytes: &[u8]) -> Result<Self, ProtocolError> {
        let hdr = VirtioBinderReqHdr::from_bytes(bytes)?;
        let hdr_len = std::mem::size_of::<VirtioBinderReqHdr>();
        let remaining = bytes.len() - hdr_len;
        let data_size = hdr.data_size as usize;
        let offsets_size = hdr.offsets_size as usize;

        if offsets_size % std::mem::size_of::<BinderSizeT>() != 0 {
            return Err(ProtocolError::InvalidOffsetsSize(offsets_size));
        }

        let total_payload = data_size
            .checked_add(offsets_size)
            .ok_or(ProtocolError::PayloadSizeMismatch {
                data_size,
                offsets_size,
                remaining,
            })?;

        if total_payload > remaining {
            return Err(ProtocolError::PayloadSizeMismatch {
                data_size,
                offsets_size,
                remaining,
            });
        }

        let data_start = hdr_len;
        let data_end = data_start + data_size;
        let data = bytes[data_start..data_end].to_vec();

        let offsets_start = data_end;
        let offsets_end = offsets_start + offsets_size;
        let offsets_raw = &bytes[offsets_start..offsets_end];
        let offsets: Vec<BinderSizeT> = if offsets_size > 0 {
            offsets_raw
                .chunks_exact(std::mem::size_of::<BinderSizeT>())
                .map(|chunk| BinderSizeT::from_ne_bytes(chunk.try_into().unwrap()))
                .collect()
        } else {
            Vec::new()
        };

        Ok(Self { hdr, data, offsets })
    }

    /// Convert request data and offsets into a `Parcel`.
    pub fn to_parcel(&self) -> Parcel {
        Parcel::from_parts(self.data.clone(), self.offsets.clone())
    }
}

/// Fully framed response packet containing header, parcel reply data bytes, and offsets array.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VirtioBinderResponse {
    pub hdr: VirtioBinderRespHdr,
    pub data: Vec<u8>,
    pub offsets: Vec<BinderSizeT>,
}

impl VirtioBinderResponse {
    /// Construct a response packet with given payload data and offsets.
    pub fn new(
        msg_id: u64,
        status: i32,
        result_code: i32,
        flags: u32,
        data: Vec<u8>,
        offsets: Vec<BinderSizeT>,
    ) -> Self {
        let data_size = data.len() as u32;
        let offsets_size = (offsets.len() * std::mem::size_of::<BinderSizeT>()) as u32;
        let hdr = VirtioBinderRespHdr::new(
            msg_id,
            status,
            result_code,
            data_size,
            offsets_size,
            flags,
        );
        Self { hdr, data, offsets }
    }

    /// Construct a success reply packet from a `Parcel`.
    pub fn ok_from_parcel(msg_id: u64, parcel: &Parcel) -> Self {
        let data = parcel.data().to_vec();
        let offsets = parcel.offsets().to_vec();
        Self::new(
            msg_id,
            binder_rt::status::STATUS_OK,
            BR_REPLY as i32,
            0,
            data,
            offsets,
        )
    }

    /// Construct an asynchronous completion response (`BR_TRANSACTION_COMPLETE`).
    pub fn one_way_complete(msg_id: u64) -> Self {
        Self {
            hdr: VirtioBinderRespHdr::new_one_way_complete(msg_id),
            data: Vec::new(),
            offsets: Vec::new(),
        }
    }

    /// Construct an error response.
    pub fn error(msg_id: u64, status: i32, result_code: i32) -> Self {
        Self {
            hdr: VirtioBinderRespHdr::new_error(msg_id, status, result_code),
            data: Vec::new(),
            offsets: Vec::new(),
        }
    }

    /// Serialize entire response into contiguous byte vector.
    pub fn serialize(&self) -> Vec<u8> {
        let hdr_bytes = self.hdr.as_bytes();
        let offsets_bytes: &[u8] = bytemuck::cast_slice(&self.offsets);
        let mut out = Vec::with_capacity(hdr_bytes.len() + self.data.len() + offsets_bytes.len());
        out.extend_from_slice(hdr_bytes);
        out.extend_from_slice(&self.data);
        out.extend_from_slice(offsets_bytes);
        out
    }

    /// Deserialize a response packet from a byte slice.
    pub fn deserialize(bytes: &[u8]) -> Result<Self, ProtocolError> {
        let hdr = VirtioBinderRespHdr::from_bytes(bytes)?;
        let hdr_len = std::mem::size_of::<VirtioBinderRespHdr>();
        let remaining = bytes.len() - hdr_len;
        let data_size = hdr.data_size as usize;
        let offsets_size = hdr.offsets_size as usize;

        if offsets_size % std::mem::size_of::<BinderSizeT>() != 0 {
            return Err(ProtocolError::InvalidOffsetsSize(offsets_size));
        }

        let total_payload = data_size
            .checked_add(offsets_size)
            .ok_or(ProtocolError::PayloadSizeMismatch {
                data_size,
                offsets_size,
                remaining,
            })?;

        if total_payload > remaining {
            return Err(ProtocolError::PayloadSizeMismatch {
                data_size,
                offsets_size,
                remaining,
            });
        }

        let data_start = hdr_len;
        let data_end = data_start + data_size;
        let data = bytes[data_start..data_end].to_vec();

        let offsets_start = data_end;
        let offsets_end = offsets_start + offsets_size;
        let offsets_raw = &bytes[offsets_start..offsets_end];
        let offsets: Vec<BinderSizeT> = if offsets_size > 0 {
            offsets_raw
                .chunks_exact(std::mem::size_of::<BinderSizeT>())
                .map(|chunk| BinderSizeT::from_ne_bytes(chunk.try_into().unwrap()))
                .collect()
        } else {
            Vec::new()
        };

        Ok(Self { hdr, data, offsets })
    }

    /// Convert response data and offsets into a `Parcel`.
    pub fn to_parcel(&self) -> Parcel {
        Parcel::from_parts(self.data.clone(), self.offsets.clone())
    }
}
