[package]
name = "vulkan2wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = { workspace = true }
naga = { workspace = true }
bytemuck = { workspace = true }
pollster = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }

[dev-dependencies]
pollster = { workspace = true }
