[package]
name = "aidl_compat"
version = "0.1.0"
edition = "2021"
description = "AOSP AIDL Interface Integration and Rust Traits Compatibility Crate"

[dependencies]
binder_rt = { path = "../binder_rt" }
thiserror = { workspace = true }
log = { workspace = true, optional = true }

[features]
default = []
log = ["dep:log"]
