[package]
name = "pms_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
aidl_compat = { path = "../aidl_compat" }
binder_rt = { path = "../binder_rt" }
binder_sys = { path = "../binder_sys" }
zip = { version = "2.2", default-features = false, features = ["deflate"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }

[dev-dependencies]
pollster = { workspace = true }
bytemuck = { workspace = true }
