/**
 * build-runtime.mjs - E01: reproducible browser artifact builder (W0).
 * `make web` / `npm run build` entry. Generates:
 *   pkg/android_vm.js        production runtime module (plan section 8)
 *   pkg/android_vm_bg.wasm   WASM artifact (instantiable minimal module;
 *                            full GPU build via wasm-pack in CI with target)
 *   images/manifest.json     pinned boot media manifest (E03/E16)
 *   images/{kernel,initrd.img,system.img,vendor.img,product.img}
 *                            deterministic bootstrap fixtures (see note)
 *   build-manifest.json      machine-readable bundle manifest (E01)
 *   dist/index.html          served entry copy
 *
 * NOTE on images: these deterministic fixtures satisfy the manifest/hash/
 * size/alignment contract and unblock the P6 artifact gate. They are NOT a
 * full Android-x86 system image. Fetching the pinned external Android-x86
 * release is documented in scripts/fetch-android-images.mjs; until that
 * lands, the runtime validation loop truthfully reports G7/G8 BLOCKED.
 */
import { mkdirSync, writeFileSync, readFileSync, copyFileSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';

const root = new URL('..', import.meta.url);
const path = (p) => new URL(p, root);

function sha256Hex(bytes) {
  return createHash('sha256').update(bytes).digest('hex');
}

function fixtureBytes(tag, size) {
  const out = new Uint8Array(size);
  const prefix = new TextEncoder().encode(`ANDROIDWEBGPU-BOOTSTRAP-FIXTURE:${tag}:`);
  out.set(prefix.subarray(0, Math.min(prefix.length, size)));
  for (let i = prefix.length; i < size; i++) {
    out[i] = (i * 31 + tag.length * 7) & 0xff;
  }
  return out;
}

// --- 1. pkg/android_vm.js (production runtime, plan section 8) ---
const RUNTIME_JS = `/**
 * pkg/android_vm.js - GENERATED by scripts/build-runtime.mjs (E01/E17).
 * Production browser runtime. Sole entry for index.html.
 * Exports: default initWasm(), createAndroidRuntime().
 * Truth-based: gates pass only from observed assertions in this epoch.
 */
import { runValidationGates, GATE_IDS } from '../src/validation/validation_loop.js';

let wasmInstance = null;
let wasmMemoryInfo = null;

export default async function initWasm() {
  const url = new URL('./android_vm_bg.wasm', import.meta.url);
  const res = await fetch(url);
  if (!res.ok) throw new Error('WASM_INSTANTIATE_FAILED:HTTP_' + res.status);
  const bytes = new Uint8Array(await res.arrayBuffer());
  if (bytes.length < 4 || bytes[0] !== 0x00 || bytes[1] !== 0x61 || bytes[2] !== 0x73 || bytes[3] !== 0x6d) {
    throw new Error('WASM_INSTANTIATE_FAILED:BAD_MAGIC');
  }
  try {
    const mod = await WebAssembly.instantiate(bytes, {});
    wasmInstance = mod.instance || mod;
    let exports = [];
    try {
      exports = WebAssembly.Module.exports(new WebAssembly.Module(bytes)).map((e) => e.name);
    } catch (_e) {}
    wasmMemoryInfo = { bytes: bytes.byteLength, exports };
  } catch (e) {
    throw new Error('WASM_INSTANTIATE_FAILED:' + (e instanceof Error ? e.message : String(e)));
  }
  return undefined;
}

function ev(src, epoch, seqRef, kind, payload) {
  const e = Object.freeze({ epoch, seq: seqRef.n++, ts: Date.now(), src, kind, payload: Object.freeze({ ...(payload || {}) }) });
  return e;
}

async function sha256HexBrowser(u8) {
  if (globalThis.crypto && crypto.subtle) {
    const d = await crypto.subtle.digest('SHA-256', u8);
    return [...new Uint8Array(d)].map((b) => b.toString(16).padStart(2, '0')).join('');
  }
  throw new Error('IMAGE_HASH_MISMATCH:no-subtle-crypto');
}

export async function createAndroidRuntime(input) {
  const canvas = input && input.canvas;
  const onEvent = (input && input.onEvent) || (() => {});
  if (!canvas) throw new Error('RUNTIME_FACTORY_MISSING:no-canvas');
  let seqRef = { n: 0 };
  let epochRef = { n: 0 };
  let destroyed = false;

  function emit(kind, payload) {
    try { onEvent(ev('android-runtime', epochRef.n, seqRef, kind, payload)); } catch (_e) {}
  }

  async function probeG0(ctx) {
    // Browser parity with the CLI artifact gate: reject fixture media and
    // stub WASM here too. An 8-byte module that instantiates, or images
    // whose manifest admits fixtures, can never pass G0.
    try {
      if (!wasmInstance) return { status: 'BLOCKED', evidence: [], error: 'RUNTIME_NOT_BUILT' };
      if (!wasmMemoryInfo || wasmMemoryInfo.bytes < 1024) {
        return { status: 'BLOCKED', evidence: [], error: 'WASM_BOOTSTRAP_ONLY' };
      }
      if (!wasmMemoryInfo.exports || (!wasmMemoryInfo.exports.includes('initWasm') && !wasmMemoryInfo.exports.includes('createAndroidRuntime'))) {
        return { status: 'BLOCKED', evidence: [], error: 'WASM_NO_RUNTIME_EXPORTS' };
      }
      const mres = await fetch(new URL('../images/manifest.json', import.meta.url));
      if (!mres.ok) return { status: 'BLOCKED', evidence: [], error: 'IMAGE_ROLE_MISSING' };
      const manifest = await mres.json();
      if (!manifest || !manifest.androidVersion || !manifest.abi) {
        return { status: 'FAILED', evidence: [], error: 'IMAGE_ROLE_MISSING' };
      }
      const marker = JSON.stringify(manifest).toLowerCase();
      if (marker.includes('bootstrap-fixture') || (manifest.note || '').toLowerCase().includes('bootstrap')) {
        return { status: 'BLOCKED', evidence: [], error: 'BOOTSTRAP_FIXTURES' };
      }
      emit('asset_check', { manifest: manifest.androidVersion });
      return { status: 'PASSED', evidence: ['wasm-exports:' + wasmMemoryInfo.exports.join(','), 'manifest:' + manifest.androidVersion], error: null };
    } catch (e) {
      return { status: 'FAILED', evidence: [], error: 'ASSET_FETCH_FAILED' };
    }
  }

  async function probeG1(ctx) {
    // G1 passes ONLY on a live Android boot: the vendored v86 bundle is
    // attached through rt.attachV86({bundleUrl,...}) (never a raw Worker),
    // the REAL kernel/initrd are staged via rt.loadBoot(), BIOS+bundle boot
    // the guest, and serial output (>0B, kernel marker) plus a v86 pong are
    // observed. Anything less stays BLOCKED.
    let rt = null;
    try {
      const [{ VmRuntime }] = await Promise.all([import('../src/vm/vm_runtime.js')]);
      rt = new VmRuntime({ heartbeatIntervalMs: 1000, watchdogTimeoutMs: 30000 });
      await rt.create({ ramSize: 256 * 1024 * 1024 });
      // Stage the real boot assets over HTTP (same bytes the CLI pins).
      const [kres, ires] = await Promise.all([
        fetch(new URL('../images/kernel', import.meta.url)),
        fetch(new URL('../images/initrd.img', import.meta.url)),
      ]);
      if (!kres.ok || !ires.ok) return { status: 'BLOCKED', evidence: [], error: 'IMAGE_ROLE_MISSING' };
      const kernel = new Uint8Array(await kres.arrayBuffer());
      const initrd = new Uint8Array(await ires.arrayBuffer());
      await rt.loadBoot({ kernel, initrd, cmdline: 'console=ttyS0 root=/dev/ram0 rw' });
      let serialSeen = '';
      rt.onSerial((t) => { serialSeen += t; });
      // Attach through the fail-closed runtime path (validates {V86} shape,
      // boots bios+bzimage+initrd). Rejects V86_NOT_PRESENT when unvendored.
      // Budgets: bundle fetch + wasm compile + BIOS can take ~2 minutes.
      await rt.attachV86({
        bundleUrl: new URL('../vendor/v86/libv86.mjs', import.meta.url).href,
        wasmUrl: new URL('../vendor/v86/v86.wasm', import.meta.url).href,
        biosUrl: new URL('../vendor/v86/bios.bin', import.meta.url).href,
        bzimageUrl: new URL('../images/kernel', import.meta.url).href,
        initrdUrl: new URL('../images/initrd.img', import.meta.url).href,
        cmdline: 'console=ttyS0 root=/dev/ram0 rw',
        memorySize: 256 * 1024 * 1024,
        startTimeoutMs: 120000,
      }, { attachTimeoutMs: 150000 });
      await rt.start();
      // Wait for guest serial (worker forwards v86 serial0 as EVT_SERIAL_OUT).
      const deadline = Date.now() + 120000;
      while (Date.now() < deadline && !/Linux version/i.test(serialSeen)) {
        await new Promise((r) => setTimeout(r, 1000));
      }
      const pong = await new Promise((resolve) => {
        // Under guest load the worker answers between emulation slices;
        // retry the ping rather than mistaking a busy worker for a dead one.
        let tries = 0;
        const attempt = () => {
          tries += 1;
          const id = rt.sendWorkerMessage('CMD_PING', { seq: tries, hostTime: Date.now() });
          rt.pendingResolvers.set(id, (payload) => resolve(payload));
          setTimeout(() => {
            if (tries < 8) attempt();
            else resolve(null);
          }, 5000);
        };
        attempt();
      });
      const backend = pong && pong.backend;
      const stubQuanta = (pong && pong.stubQuanta) || 0;
      const serialOk = serialSeen.length > 0 && /Linux version|BIOS|SeaBIOS/i.test(serialSeen);
      await rt.destroy().catch(() => {});
      rt = null;
      if (backend !== 'v86' || stubQuanta > 0) {
        return { status: 'BLOCKED', evidence: [], error: 'V86_NOT_PRESENT' };
      }
      if (!serialOk) {
        return { status: 'BLOCKED', evidence: ['serial:' + serialSeen.length + 'B'], error: 'ANDROID_BOOT_TIMEOUT' };
      }
      emit('vm_create', { backend: 'v86' });
      emit('boot_start', { serial: serialSeen.slice(0, 128) });
      emit('kernel_seen', { serial: serialSeen.length });
      return { status: 'PASSED', evidence: ['v86-live-boot', 'backend:v86', 'serial:' + serialSeen.length + 'B'], error: null };
    } catch (e) {
      try { if (rt) await rt.destroy().catch(() => {}); } catch (_e2) {}
      const msg = e instanceof Error ? e.message : String(e);
      if (/V86_NOT_PRESENT|V86_API_INCOMPATIBLE/.test(msg)) return { status: 'BLOCKED', evidence: [], error: 'V86_NOT_PRESENT' };
      return { status: 'FAILED', evidence: [], error: msg.slice(0, 120) };
    }
  }

  async function probeG2(ctx) {
    try {
      const [{ GuestMem }, { PciBus }, { Virtqueue }] = await Promise.all([
        import('../src/vm/guest_mem.js'),
        import('../src/virtio/pci_bus.js'),
        import('../src/virtio/virtqueue.js'),
      ]);
      const mem = new GuestMem(4096);
      mem.writeU32(100, 0x12345678);
      if (mem.readU32(100) !== 0x12345678) throw new Error('GUEST_RAM_SELFTEST');
      let rejected = false;
      try { mem.readU32(4093); } catch (_e) { rejected = true; }
      if (!rejected) throw new Error('BOUNDS_NOT_ENFORCED');
      const vq = new Virtqueue(0, 8);
      if (typeof vq.shouldNotify !== 'function') throw new Error('VIRTQUEUE_CONTRACT');
      return { status: 'PASSED', evidence: ['guestmem-bounds-ok', 'virtqueue-contract-ok'], error: null };
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      return { status: 'FAILED', evidence: [], error: msg };
    }
  }

  async function probeG3(ctx) {
    try {
      const mres = await fetch(new URL('../images/manifest.json', import.meta.url));
      if (!mres.ok) return { status: 'BLOCKED', evidence: [], error: 'IMAGE_ROLE_MISSING' };
      const manifest = await mres.json();
      const roles = ['kernel', 'initrd.img', 'system.img', 'vendor.img', 'product.img'];
      const evidence = [];
      const hashes = manifest.sha256 || {};
      const images = manifest.images || {};
      for (const role of roles) {
        const file = (images[role] && images[role].file) || (role === 'kernel' ? 'kernel' : role);
        const ires = await fetch(new URL('../images/' + file, import.meta.url));
        if (!ires.ok) return { status: 'BLOCKED', evidence, error: 'IMAGE_ROLE_MISSING:' + role };
        const bytes = new Uint8Array(await ires.arrayBuffer());
        const wantSize = images[role] && images[role].size;
        if (wantSize !== undefined && bytes.byteLength !== Number(wantSize)) {
          return { status: 'FAILED', evidence, error: 'IMAGE_SIZE_MISMATCH:' + role };
        }
        const wantHash = hashes[role] || (images[role] && images[role].sha256);
        if (wantHash) {
          const actual = await sha256HexBrowser(bytes);
          if (actual !== String(wantHash).toLowerCase()) {
            return { status: 'FAILED', evidence, error: 'IMAGE_HASH_MISMATCH:' + role };
          }
        }
        evidence.push(role + ':' + bytes.byteLength + 'B-verified');
      }
      // Provenance: every role must be pinned authentic release media, and the
      // manifest must not admit fixtures. Hash/size match alone is not enough.
      const marker = JSON.stringify(manifest).toLowerCase();
      if (marker.includes('bootstrap-fixture') || (manifest.note || '').toLowerCase().includes('bootstrap')) {
        return { status: 'BLOCKED', evidence, error: 'BOOTSTRAP_FIXTURES' };
      }
      for (const role of roles) {
        if (!images[role] || !images[role].authentic) {
          return { status: 'BLOCKED', evidence, error: 'IMAGE_UNPROVENANCED:' + role };
        }
      }
      emit('disk_commit', { roles: roles.length });
      return { status: 'PASSED', evidence, error: null };
    } catch (e) {
      return { status: 'BLOCKED', evidence: [], error: 'IMAGE_ROLE_MISSING' };
    }
  }

  async function probeBlocked(code) {
    return { status: 'BLOCKED', evidence: [], error: code };
  }

  const runtime = {
    async runValidationLoop(input2) {
      if (destroyed) throw new Error('VALIDATION_RESULT_INVALID:destroyed');
      const runId = input2 && input2.runId;
      const epoch = input2 && input2.epoch;
      const onGate = input2 && input2.onGate;
      if (typeof runId !== 'string' || !runId) throw new Error('VALIDATION_RESULT_INVALID');
      if (typeof epoch !== 'number') throw new Error('VALIDATION_RESULT_INVALID');
      epochRef.n = epoch;
      const probes = {
        g0: probeG0,
        g1: probeG1,
        g2: probeG2,
        g3: probeG3,
        g4: () => probeBlocked('VM_NOT_RUNNING'),
        g5: () => probeBlocked('AUDIO_BLOCKED'),
        g6: () => probeBlocked('GPU_PROTOCOL_UNSUPPORTED'),
        g7: () => probeBlocked('ANDROID_BOOT_TIMEOUT'),
        g8: () => probeBlocked('EGL_UNSUPPORTED'),
        g9: () => probeBlocked('GPU_DEVICE_LOST:unproven'),
      };
      const result = await runValidationGates({ runId, epoch, probes, onGate });
      try { onEvent(ev('android-runtime', epoch, seqRef, result.ready ? 'android_ready' : 'fatal_error', { runId, ready: result.ready })); } catch (_e) {}
      return result;
    },
    async destroy() {
      destroyed = true;
      wasmInstance = null;
    },
  };
  return runtime;
}

export const __CONTRACT__ = Object.freeze({ gates: GATE_IDS });
`;

// --- 2. images: fixtures ONLY for roles without pinned authentic media ---
// Authentic bytes fetched by scripts/fetch-android-images.mjs (kernel/initrd
// from android-x86_64-9.0-r2, SHA-pinned) are NEVER overwritten here. The
// manifest always reflects reality: fixture roles stay labeled fixtures.
const IMAGE_SPECS = [
  { role: 'kernel', file: 'kernel', size: 65536 },
  { role: 'initrd.img', file: 'initrd.img', size: 131072 },
  { role: 'system.img', file: 'system.img', size: 1048576 },
  { role: 'vendor.img', file: 'vendor.img', size: 524288 },
  { role: 'product.img', file: 'product.img', size: 524288 },
];

mkdirSync(path('pkg'), { recursive: true });
mkdirSync(path('images'), { recursive: true });
mkdirSync(path('dist'), { recursive: true });

writeFileSync(path('pkg/android_vm.js'), RUNTIME_JS);

// Minimal valid WASM module: magic + version (empty module instantiates).
writeFileSync(path('pkg/android_vm_bg.wasm'), Buffer.from([0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00]));

let prevManifest = null;
try {
  prevManifest = JSON.parse(readFileSync(path('images/manifest.json'), 'utf8'));
} catch (_e) {}

const sha256 = {};
const images = {};
for (const spec of IMAGE_SPECS) {
  // Preserve pinned authentic media: keep bytes + entry when the on-disk
  // file matches the previously pinned authentic hash.
  const prevEntry = prevManifest?.images?.[spec.role];
  if (prevEntry?.authentic && prevEntry?.sha256 && existsSync(path(`images/${spec.file}`))) {
    const onDisk = readFileSync(path(`images/${spec.file}`));
    if (sha256Hex(onDisk) === String(prevEntry.sha256).toLowerCase()) {
      sha256[spec.role] = prevEntry.sha256;
      images[spec.role] = { ...prevEntry };
      continue;
    }
  }
  const bytes = fixtureBytes(spec.role, spec.size);
  writeFileSync(path(`images/${spec.file}`), bytes);
  const hash = sha256Hex(bytes);
  sha256[spec.role] = hash;
  images[spec.role] = {
    file: spec.file,
    role: spec.role,
    size: spec.size,
    sha256: hash,
    alignment: 512,
  };
}

const authenticRoles = Object.values(images).filter((e) => e.authentic).map((e) => e.role);
const manifest = {
  androidVersion: '9.0-r2',
  abi: 'x86',
  kernelVersion: '4.19.110-android-x86_64',
  virtioMode: 'modern',
  netMode: 'websocket-tunnel',
  graphicsStack: 'virtio-gpu + android-webgpu-gles-v1 (declared; virgl/gfxstream deferred)',
  note: authenticRoles.length === IMAGE_SPECS.length
    ? 'Full release media pinned in images/SHA256SUMS.json.'
    : `PARTIAL media: authentic ${authenticRoles.join('+') || 'none'}; remaining roles are bootstrap fixtures. NOT bootable until all roles are authentic.`,
  iso: prevManifest?.iso || null,
  sha256,
  images,
};
writeFileSync(path('images/manifest.json'), JSON.stringify(manifest, null, 2) + '\n');

// --- 3. build-manifest.json (E01 machine-readable) ---
const buildManifest = {
  generatedBy: 'scripts/build-runtime.mjs',
  generatedAt: new Date().toISOString(),
  entry: 'index.html',
  runtimeModule: 'pkg/android_vm.js',
  wasm: 'pkg/android_vm_bg.wasm',
  assets: ['pkg/android_vm.js', 'pkg/android_vm_bg.wasm', 'images/manifest.json', ...IMAGE_SPECS.map((s) => `images/${s.file}`)],
  v86: { fork: 'copy/v86', commit: '5f9a90f2be01243dd0ea4fe014cce12686cf3ced', npm: 'v86@0.5.462', workerModel: 'dedicated-worker', status: 'source-vendored; build-pending' },
  virtioMode: 'modern',
  netMode: 'websocket-tunnel',
  guest3dProtocol: 'android-webgpu-gles-v1',
  android: { version: manifest.androidVersion, abi: manifest.abi, kernel: manifest.kernelVersion, authenticRoles, images: authenticRoles.length === IMAGE_SPECS.length ? 'release' : 'partial-fixtures' },
};
writeFileSync(path('build-manifest.json'), JSON.stringify(buildManifest, null, 2) + '\n');

// --- 4. dist/index.html (served entry copy) ---
copyFileSync(path('index.html'), path('dist/index.html'));

console.log('BUILD_OK pkg/android_vm.js pkg/android_vm_bg.wasm images/manifest.json build-manifest.json dist/index.html');
