//! P4 system-register end-to-end fixtures (2026-10-03, feat/emu-p4-impl).
//!
//! Executes the exact MRS/MSR words from the P4 coverage backlog (186
//! encodings: SVE control, EL2, GICv3 CPU MSRs, debug breakpoint/watchpoint
//! regs, PMU cycle counter, IMPDEF constants/no-ops) through the real
//! decode -> lift -> compile -> execute pipeline (`Orchestrator::step_vcpu`)
//! and asserts the semantic outcome: GPR values AND the persistent sysreg
//! state. Fixtures live in `fixtures/sysreg_p4_*.json` (generated by the P4
//! fixture generator); this file is the runner.
//!
//! Memory: one `Orchestrator` (~1GiB) per sequence, sequential within each
//! test. Run with `-- --test-threads=1` on the sandbox.

use pathn_contracts::cpu::SysReg;
use std::collections::HashMap;
use u12_orchestrator::{Orchestrator, StepOutcome, RAM_BASE, TIMER_CYCLES_PER_STEP};

fn sysreg_by_name(name: &str) -> SysReg {
    match name {
        "dbgbvr0_el1" => SysReg::Dbgbvr0,
        "dbgbvr1_el1" => SysReg::Dbgbvr1,
        "dbgbvr2_el1" => SysReg::Dbgbvr2,
        "dbgbvr3_el1" => SysReg::Dbgbvr3,
        "dbgbvr4_el1" => SysReg::Dbgbvr4,
        "dbgbvr5_el1" => SysReg::Dbgbvr5,
        "dbgbvr6_el1" => SysReg::Dbgbvr6,
        "dbgbvr7_el1" => SysReg::Dbgbvr7,
        "dbgbvr8_el1" => SysReg::Dbgbvr8,
        "dbgbvr9_el1" => SysReg::Dbgbvr9,
        "dbgbvr10_el1" => SysReg::Dbgbvr10,
        "dbgbvr11_el1" => SysReg::Dbgbvr11,
        "dbgbvr12_el1" => SysReg::Dbgbvr12,
        "dbgbvr13_el1" => SysReg::Dbgbvr13,
        "dbgbvr14_el1" => SysReg::Dbgbvr14,
        "dbgbvr15_el1" => SysReg::Dbgbvr15,
        "dbgbcr0_el1" => SysReg::Dbgbcr0,
        "dbgbcr1_el1" => SysReg::Dbgbcr1,
        "dbgbcr2_el1" => SysReg::Dbgbcr2,
        "dbgbcr3_el1" => SysReg::Dbgbcr3,
        "dbgbcr4_el1" => SysReg::Dbgbcr4,
        "dbgbcr5_el1" => SysReg::Dbgbcr5,
        "dbgbcr6_el1" => SysReg::Dbgbcr6,
        "dbgbcr7_el1" => SysReg::Dbgbcr7,
        "dbgbcr8_el1" => SysReg::Dbgbcr8,
        "dbgbcr9_el1" => SysReg::Dbgbcr9,
        "dbgbcr10_el1" => SysReg::Dbgbcr10,
        "dbgbcr11_el1" => SysReg::Dbgbcr11,
        "dbgbcr12_el1" => SysReg::Dbgbcr12,
        "dbgbcr13_el1" => SysReg::Dbgbcr13,
        "dbgbcr14_el1" => SysReg::Dbgbcr14,
        "dbgbcr15_el1" => SysReg::Dbgbcr15,
        "dbgwvr0_el1" => SysReg::Dbgwvr0,
        "dbgwvr1_el1" => SysReg::Dbgwvr1,
        "dbgwvr2_el1" => SysReg::Dbgwvr2,
        "dbgwvr3_el1" => SysReg::Dbgwvr3,
        "dbgwvr4_el1" => SysReg::Dbgwvr4,
        "dbgwvr5_el1" => SysReg::Dbgwvr5,
        "dbgwvr6_el1" => SysReg::Dbgwvr6,
        "dbgwvr7_el1" => SysReg::Dbgwvr7,
        "dbgwvr8_el1" => SysReg::Dbgwvr8,
        "dbgwvr9_el1" => SysReg::Dbgwvr9,
        "dbgwvr10_el1" => SysReg::Dbgwvr10,
        "dbgwvr11_el1" => SysReg::Dbgwvr11,
        "dbgwvr12_el1" => SysReg::Dbgwvr12,
        "dbgwvr13_el1" => SysReg::Dbgwvr13,
        "dbgwvr14_el1" => SysReg::Dbgwvr14,
        "dbgwvr15_el1" => SysReg::Dbgwvr15,
        "dbgwcr0_el1" => SysReg::Dbgwcr0,
        "dbgwcr1_el1" => SysReg::Dbgwcr1,
        "dbgwcr2_el1" => SysReg::Dbgwcr2,
        "dbgwcr3_el1" => SysReg::Dbgwcr3,
        "dbgwcr4_el1" => SysReg::Dbgwcr4,
        "dbgwcr5_el1" => SysReg::Dbgwcr5,
        "dbgwcr6_el1" => SysReg::Dbgwcr6,
        "dbgwcr7_el1" => SysReg::Dbgwcr7,
        "dbgwcr8_el1" => SysReg::Dbgwcr8,
        "dbgwcr9_el1" => SysReg::Dbgwcr9,
        "dbgwcr10_el1" => SysReg::Dbgwcr10,
        "dbgwcr11_el1" => SysReg::Dbgwcr11,
        "dbgwcr12_el1" => SysReg::Dbgwcr12,
        "dbgwcr13_el1" => SysReg::Dbgwcr13,
        "dbgwcr14_el1" => SysReg::Dbgwcr14,
        "dbgwcr15_el1" => SysReg::Dbgwcr15,
        "vpidr_el2" => SysReg::VpidrEl2,
        "vmpidr_el2" => SysReg::VmpidrEl2,
        "cptr_el2" => SysReg::CptrEl2,
        "mdcr_el2" => SysReg::MdcrEl2,
        "hstr_el2" => SysReg::HstrEl2,
        "zcr_el2" => SysReg::ZcrEl2,
        "vbar_el2" => SysReg::VbarEl2,
        "ich_hcr_el2" => SysReg::IchHcrEl2,
        "vttbr_el2" => SysReg::VttbrEl2,
        "spsr_el2" => SysReg::SpsrEl2,
        "elr_el2" => SysReg::ElrEl2,
        "pmscr_el2" => SysReg::PmscrEl2,
        "icc_sre_el2" => SysReg::IccSreEl2,
        "icc_bpr1_el1" => SysReg::IccBpr1El1,
        "icc_ap0r0_el1" => SysReg::IccAp0r0El1,
        "icc_ap0r1_el1" => SysReg::IccAp0r1El1,
        "icc_ap0r2_el1" => SysReg::IccAp0r2El1,
        "icc_ap0r3_el1" => SysReg::IccAp0r3El1,
        "icc_ap1r0_el1" => SysReg::IccAp1r0El1,
        "icc_ap1r1_el1" => SysReg::IccAp1r1El1,
        "icc_ap1r2_el1" => SysReg::IccAp1r2El1,
        "icc_ap1r3_el1" => SysReg::IccAp1r3El1,
        "icc_sgi1r_el1" => SysReg::IccSgi1rEl1,
        "disr_el1" => SysReg::DisrEl1,
        "lorc_el1" => SysReg::LorcEl1,
        "pmccntr_el0" => SysReg::PmccntrEl0,
        "zcr_el1" => SysReg::ZcrEl1,
        other => panic!("sysreg_p4 fixture: unknown sysreg {other}"),
    }
}

#[derive(Debug, serde::Deserialize)]
struct Step {
    word: u32,
    disasm: String,
}

#[derive(Debug, serde::Deserialize)]
struct TvalCheck {
    msr_step: usize,
    mrs_step: usize,
    dst_reg: usize,
    written: u64,
}

#[derive(Debug, serde::Deserialize)]
struct Sequence {
    name: String,
    steps: Vec<Step>,
    #[serde(default)]
    expected_regs: HashMap<String, u64>,
    #[serde(default)]
    expected_sysregs: HashMap<String, u64>,
    #[serde(default)]
    tvals: Vec<TvalCheck>,
}

fn run_sequences(json: &str) {
    let seqs: Vec<Sequence> = serde_json::from_str(json).expect("fixture parses");
    for seq in &seqs {
        let mut o = Orchestrator::new();
        o.machine_mut().cpu[0].pc = RAM_BASE;
        // Seed the physical counter so TVAL arithmetic is exact.
        o.machine_mut().irq.timer_count = 1_000_000;
        o.machine_mut().cpu[0].sysregs.cntpct_el0 = 1_000_000;
        for (i, step) in seq.steps.iter().enumerate() {
            let addr = RAM_BASE + (i as u64) * 4;
            let off = (addr - RAM_BASE) as usize;
            o.machine_mut().ram[off..off + 4].copy_from_slice(&step.word.to_le_bytes());
        }
        for (i, step) in seq.steps.iter().enumerate() {
            let outcome = o.step_vcpu();
            assert_eq!(
                outcome,
                StepOutcome::Continue,
                "seq {} step {i} ({}) did not Continue: {outcome:?}",
                seq.name,
                step.disasm
            );
        }
        let cpu = &o.machine().cpu[0];
        for (reg, want) in &seq.expected_regs {
            let idx: usize = reg.parse().expect("reg index");
            assert_eq!(
                cpu.regs[idx], *want,
                "seq {} x{idx}: got {:#x}, want {:#x}",
                seq.name, cpu.regs[idx], want
            );
        }
        for (name, want) in &seq.expected_sysregs {
            let got = o.machine().cpu[0].sysregs.load(sysreg_by_name(name));
            assert_eq!(
                got, *want,
                "seq {} sysreg {name}: got {:#x}, want {:#x}",
                seq.name, got, want
            );
        }
        for t in &seq.tvals {
            // TVAL read = written - ticks advanced between the MSR and MRS.
            let ticks = (t.mrs_step - t.msr_step) as u64;
            let want = t.written.wrapping_sub(TIMER_CYCLES_PER_STEP * ticks);
            let got = cpu.regs[t.dst_reg];
            assert_eq!(
                got, want,
                "seq {} tval x{}: got {got:#x}, want {want:#x}",
                seq.name, t.dst_reg
            );
        }
        // Every step advanced PC by 4.
        assert_eq!(
            cpu.pc,
            RAM_BASE + (seq.steps.len() as u64) * 4,
            "seq {}: pc did not advance past all steps",
            seq.name
        );
    }
}

#[test]
fn p4_zcr_el1_e2e() {
    run_sequences(include_str!("fixtures/sysreg_p4_zcr.json"));
}

#[test]
fn p4_debug_all64_e2e() {
    run_sequences(include_str!("fixtures/sysreg_p4_debug.json"));
}

#[test]
fn p4_el2_msrs_e2e() {
    run_sequences(include_str!("fixtures/sysreg_p4_el2.json"));
}

#[test]
fn p4_gic_cpu_msrs_e2e() {
    run_sequences(include_str!("fixtures/sysreg_p4_gic.json"));
}

#[test]
fn p4_misc_disr_lorc_pmccntr_tval_e2e() {
    run_sequences(include_str!("fixtures/sysreg_p4_misc.json"));
}

#[test]
fn p4_impdef_constants_and_nops_e2e() {
    run_sequences(include_str!("fixtures/sysreg_p4_impdef.json"));
}
