//! QEMU-oracle test vector integration test harness for F2 branch instructions.
//!
//! Follows LLD Box Pure Function & Explicit Contract Rule:
//! Evaluates test vectors generated by scripts/testgen against our emulator's
//! real execution pipeline (u12 fast path where available, else normal
//! decode -> lift -> compile -> JIT path).

use serde::{Deserialize, Serialize};
use u12_orchestrator::arm64::FLAGS_NZCV_MASK;
use u12_orchestrator::{Orchestrator, StepOutcome, RAM_BASE};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct MemoryEntry {
    pub addr: u64,
    pub data: Vec<u8>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CpuRegs {
    pub regs: [u64; 31],
    pub sp: u64,
    pub pstate: u64,
    pub pc: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TestVector {
    pub name: String,
    pub word: u32,
    pub disasm: String,
    pub initial_regs: CpuRegs,
    #[serde(default)]
    pub initial_mem: Vec<MemoryEntry>,
    pub expected_regs: CpuRegs,
    #[serde(default)]
    pub expected_mem: Vec<MemoryEntry>,
}

/// Executes a single test vector against the production emulator pipeline.
pub fn execute_vector(vector: &TestVector) -> Result<(), String> {
    let mut orchestrator = Orchestrator::new();

    // 1. Set initial registers and machine state
    orchestrator.machine_mut().cpu[0].regs = vector.initial_regs.regs;
    orchestrator.machine_mut().cpu[0].sp = vector.initial_regs.sp;
    orchestrator.machine_mut().cpu[0].pstate = vector.initial_regs.pstate;
    orchestrator.machine_mut().cpu[0].pc = vector.initial_regs.pc;

    // 2. Write instruction word to guest RAM at PC
    if vector.initial_regs.pc < RAM_BASE {
        return Err(format!(
            "PC {:#x} below RAM_BASE {:#x}",
            vector.initial_regs.pc, RAM_BASE
        ));
    }
    let ram_offset = (vector.initial_regs.pc - RAM_BASE) as usize;
    if ram_offset + 4 > orchestrator.machine().ram.len() {
        return Err(format!(
            "PC {:#x} out of RAM bounds",
            vector.initial_regs.pc
        ));
    }
    orchestrator.machine_mut().ram[ram_offset..ram_offset + 4]
        .copy_from_slice(&vector.word.to_le_bytes());

    // 3. Write initial memory entries
    for entry in &vector.initial_mem {
        if entry.addr < RAM_BASE {
            return Err(format!("Memory addr {:#x} below RAM_BASE", entry.addr));
        }
        let off = (entry.addr - RAM_BASE) as usize;
        orchestrator.machine_mut().ram[off..off + entry.data.len()].copy_from_slice(&entry.data);
    }

    // 4. Step through the REAL execution pipeline
    let outcome = orchestrator.step_vcpu();
    if outcome != StepOutcome::Continue {
        return Err(format!(
            "step_vcpu returned non-Continue outcome: {:?}",
            outcome
        ));
    }

    // 5. Compare final architectural state against QEMU expected state
    let cpu = &orchestrator.machine().cpu[0];
    let mut diffs = Vec::new();

    if cpu.pc != vector.expected_regs.pc {
        diffs.push(format!(
            "PC mismatch: got {:#x}, expected {:#x}",
            cpu.pc, vector.expected_regs.pc
        ));
    }

    if cpu.sp != vector.expected_regs.sp {
        diffs.push(format!(
            "SP mismatch: got {:#x}, expected {:#x}",
            cpu.sp, vector.expected_regs.sp
        ));
    }

    let actual_flags = cpu.pstate & FLAGS_NZCV_MASK;
    let expected_flags = vector.expected_regs.pstate & FLAGS_NZCV_MASK;
    if actual_flags != expected_flags {
        diffs.push(format!(
            "NZCV flags mismatch: got {:#x}, expected {:#x}",
            actual_flags, expected_flags
        ));
    }

    for (i, (&actual, &expected)) in cpu
        .regs
        .iter()
        .zip(vector.expected_regs.regs.iter())
        .enumerate()
    {
        if actual != expected {
            diffs.push(format!(
                "X{} mismatch: got {:#x} ({}), expected {:#x} ({})",
                i, actual, actual, expected, expected
            ));
        }
    }

    // 6. Check expected memory
    for entry in &vector.expected_mem {
        let off = (entry.addr - RAM_BASE) as usize;
        let actual_slice = &orchestrator.machine().ram[off..off + entry.data.len()];
        if actual_slice != entry.data.as_slice() {
            diffs.push(format!(
                "Memory mismatch at {:#x}: got {:?}, expected {:?}",
                entry.addr, actual_slice, entry.data
            ));
        }
    }

    if diffs.is_empty() {
        Ok(())
    } else {
        Err(diffs.join("; "))
    }
}

fn run_suite(name: &str, json_str: &str, min_count: usize) {
    let vectors: Vec<TestVector> = serde_json::from_str(json_str)
        .unwrap_or_else(|e| panic!("Failed to deserialize {name}: {e}"));

    assert!(
        vectors.len() >= min_count,
        "Expected at least {min_count} test vectors for {name}, found {}",
        vectors.len()
    );

    let mut passed = 0;
    let mut failed = 0;
    let mut failure_details = Vec::new();

    for (idx, vec) in vectors.iter().enumerate() {
        match execute_vector(vec) {
            Ok(()) => {
                passed += 1;
            }
            Err(e) => {
                failed += 1;
                failure_details.push(format!("[Vector #{:03}] {}: {}", idx, vec.name, e));
            }
        }
    }

    println!("\n=== QEMU Oracle Vector Test Report ===");
    println!("Instruction Family: {name}");
    println!("Total Vectors Evaluated: {}", vectors.len());
    println!("Passed: {}", passed);
    println!("Failed: {}", failed);
    if !failure_details.is_empty() {
        println!("\nFailures:");
        for f in &failure_details {
            println!("  {}", f);
        }
    }
    println!("======================================\n");

    assert_eq!(failed, 0, "{failed} vectors failed for {name}");
}

#[test]
fn test_b_cond_qemu_vectors() {
    run_suite("B.cond", include_str!("fixtures/b_cond.json"), 50);
}

#[test]
fn test_cbz_qemu_vectors() {
    run_suite("CBZ", include_str!("fixtures/cbz.json"), 50);
}

#[test]
fn test_cbnz_qemu_vectors() {
    run_suite("CBNZ", include_str!("fixtures/cbnz.json"), 50);
}

#[test]
fn test_tbz_qemu_vectors() {
    run_suite("TBZ", include_str!("fixtures/tbz.json"), 50);
}

#[test]
fn test_tbnz_qemu_vectors() {
    run_suite("TBNZ", include_str!("fixtures/tbnz.json"), 50);
}

#[test]
fn test_b_imm_qemu_vectors() {
    run_suite("B (immediate)", include_str!("fixtures/b_imm.json"), 10);
}

#[test]
fn test_bl_imm_qemu_vectors() {
    run_suite("BL (immediate)", include_str!("fixtures/bl_imm.json"), 10);
}
#[test]
fn test_ldr_immediate_qemu_vectors() {
    let json_str = include_str!("fixtures/ldr_imm.json");
    let vectors: Vec<TestVector> =
        serde_json::from_str(json_str).expect("Failed to deserialize ldr_imm.json");

    assert!(
        vectors.len() >= 20,
        "Expected at least 20 test vectors, found {}",
        vectors.len()
    );

    let mut passed = 0;
    let mut failed = 0;
    let mut failure_details = Vec::new();

    for (idx, vec) in vectors.iter().enumerate() {
        match execute_vector(vec) {
            Ok(()) => {
                passed += 1;
            }
            Err(e) => {
                failed += 1;
                failure_details.push(format!("[Vector #{:03}] {}: {}", idx, vec.name, e));
            }
        }
    }

    println!("\n=== QEMU Oracle Vector Test Report ===");
    println!("Instruction Family: LDR (immediate)");
    println!("Total Vectors Evaluated: {}", vectors.len());
    println!("Passed: {}", passed);
    println!("Failed: {}", failed);
    if !failure_details.is_empty() {
        println!("\nFailures:");
        for f in &failure_details {
            println!("  {}", f);
        }
    }
    println!("======================================\n");
}

#[test]
fn test_str_immediate_qemu_vectors() {
    let json_str = include_str!("fixtures/str_imm.json");
    let vectors: Vec<TestVector> =
        serde_json::from_str(json_str).expect("Failed to deserialize str_imm.json");

    assert!(
        vectors.len() >= 20,
        "Expected at least 20 test vectors, found {}",
        vectors.len()
    );

    let mut passed = 0;
    let mut failed = 0;
    let mut failure_details = Vec::new();

    for (idx, vec) in vectors.iter().enumerate() {
        match execute_vector(vec) {
            Ok(()) => {
                passed += 1;
            }
            Err(e) => {
                failed += 1;
                failure_details.push(format!("[Vector #{:03}] {}: {}", idx, vec.name, e));
            }
        }
    }

    println!("\n=== QEMU Oracle Vector Test Report ===");
    println!("Instruction Family: STR (immediate)");
    println!("Total Vectors Evaluated: {}", vectors.len());
    println!("Passed: {}", passed);
    println!("Failed: {}", failed);
    if !failure_details.is_empty() {
        println!("\nFailures:");
        for f in &failure_details {
            println!("  {}", f);
        }
    }
    println!("======================================\n");
}
