/**
 * error_codes.js - W0 frozen contract: stable error codes (E18).
 * Every failure on the browser acceptance path uses one of these codes.
 * Codes are stable across runs; human hints accompany each code in logs.
 */

export const ERROR_CODES = Object.freeze({
  // Runtime / bundle (G0)
  RUNTIME_NOT_BUILT: 'RUNTIME_NOT_BUILT',
  RUNTIME_WASM_INIT_MISSING: 'RUNTIME_WASM_INIT_MISSING',
  RUNTIME_FACTORY_MISSING: 'RUNTIME_FACTORY_MISSING',
  VALIDATION_LOOP_CONTRACT_MISSING: 'VALIDATION_LOOP_CONTRACT_MISSING',
  WEBGPU_UNAVAILABLE: 'WEBGPU_UNAVAILABLE',
  WASM_INSTANTIATE_FAILED: 'WASM_INSTANTIATE_FAILED',
  ASSET_FETCH_FAILED: 'ASSET_FETCH_FAILED',
  // VM (G1)
  V86_NOT_PRESENT: 'V86_NOT_PRESENT',
  VM_NOT_RUNNING: 'VM_NOT_RUNNING',
  WATCHDOG_TIMEOUT: 'WATCHDOG_TIMEOUT',
  GUEST_RAM_NOT_SHARED: 'GUEST_RAM_NOT_SHARED',
  CPU_TRAP: 'CPU_TRAP',
  // Virtio core (G2)
  DESCRIPTOR_LOOP_DETECTED: 'DESCRIPTOR_LOOP_DETECTED',
  DMA_OUT_OF_BOUNDS: 'DMA_OUT_OF_BOUNDS',
  MALFORMED_DESCRIPTOR_CHAIN: 'MALFORMED_DESCRIPTOR_CHAIN',
  FEATURES_NOT_NEGOTIATED: 'FEATURES_NOT_NEGOTIATED',
  // Block / storage (G3)
  IMAGE_ROLE_MISSING: 'IMAGE_ROLE_MISSING',
  IMAGE_HASH_MISMATCH: 'IMAGE_HASH_MISMATCH',
  IMAGE_SIZE_MISMATCH: 'IMAGE_SIZE_MISMATCH',
  STORAGE_QUOTA_EXCEEDED: 'STORAGE_QUOTA_EXCEEDED',
  DISK_OUT_OF_BOUNDS: 'DISK_OUT_OF_BOUNDS',
  // Console / input (G4)
  CONSOLE_OVERFLOW: 'CONSOLE_OVERFLOW',
  INPUT_QUEUE_BLOCKED: 'INPUT_QUEUE_BLOCKED',
  // Net / audio (G5)
  NET_LINK_DOWN: 'NET_LINK_DOWN',
  NET_PROXY_DENIED: 'NET_PROXY_DENIED',
  AUDIO_BLOCKED: 'AUDIO_BLOCKED',
  AUDIO_UNDERRUN: 'AUDIO_UNDERRUN',
  // GPU (G6)
  GPU_RESOURCE_INVALID: 'GPU_RESOURCE_INVALID',
  GPU_FENCE_OUT_OF_ORDER: 'GPU_FENCE_OUT_OF_ORDER',
  GPU_PROTOCOL_UNSUPPORTED: 'GPU_PROTOCOL_UNSUPPORTED',
  GPU_DEVICE_LOST: 'GPU_DEVICE_LOST',
  // Android guest (G7/G8)
  ANDROID_BOOT_TIMEOUT: 'ANDROID_BOOT_TIMEOUT',
  SURFACE_FLINGER_UNREADY: 'SURFACE_FLINGER_UNREADY',
  EGL_UNSUPPORTED: 'EGL_UNSUPPORTED',
  // Validation (G9 / loop)
  VALIDATION_GATE_ID_INVALID: 'VALIDATION_GATE_ID_INVALID',
  VALIDATION_GATE_STATUS_INVALID: 'VALIDATION_GATE_STATUS_INVALID',
  VALIDATION_GATE_MISSING: 'VALIDATION_GATE_MISSING',
  VALIDATION_RESULT_INVALID: 'VALIDATION_RESULT_INVALID',
  VALIDATION_STALE_EPOCH: 'VALIDATION_STALE_EPOCH',
});

export const ERROR_HINTS = Object.freeze({
  RUNTIME_NOT_BUILT: 'Run `make web` to generate pkg/android_vm.js and images/.',
  V86_NOT_PRESENT: 'Vendored v86 emulator is absent; VM cannot execute guest code.',
  GUEST_RAM_NOT_SHARED: 'Guest RAM must be SharedArrayBuffer (COOP/COEP headers required).',
  IMAGE_HASH_MISMATCH: 'Boot image failed SHA-256 verification; re-download the pinned image.',
  NET_LINK_DOWN: 'Declared browser net mode is unavailable; guest link is down by design.',
  GPU_DEVICE_LOST: 'WebGPU device was lost; re-create device and re-attach scanout resources.',
});

export function errorInfo(code) {
  return { code, hint: ERROR_HINTS[code] || 'See plan.md validation matrix.' };
}
