/**
 * pkg/android_vm.js - GENERATED by scripts/build-runtime.mjs (E01/E17).
 * Production browser runtime. Sole entry for index.html.
 * Exports: default initWasm(), createAndroidRuntime().
 * Truth-based: gates pass only from observed assertions in this epoch.
 */
import { runValidationGates, GATE_IDS } from '../src/validation/validation_loop.js';

let wasmInstance = null;
let wasmMemoryInfo = null;

export default async function initWasm() {
  const url = new URL('./android_vm_bg.wasm', import.meta.url);
  const res = await fetch(url);
  if (!res.ok) throw new Error('WASM_INSTANTIATE_FAILED:HTTP_' + res.status);
  const bytes = new Uint8Array(await res.arrayBuffer());
  if (bytes.length < 4 || bytes[0] !== 0x00 || bytes[1] !== 0x61 || bytes[2] !== 0x73 || bytes[3] !== 0x6d) {
    throw new Error('WASM_INSTANTIATE_FAILED:BAD_MAGIC');
  }
  try {
    const mod = await WebAssembly.instantiate(bytes, {});
    wasmInstance = mod.instance || mod;
    let exports = [];
    try {
      exports = WebAssembly.Module.exports(new WebAssembly.Module(bytes)).map((e) => e.name);
    } catch (_e) {}
    wasmMemoryInfo = { bytes: bytes.byteLength, exports };
  } catch (e) {
    throw new Error('WASM_INSTANTIATE_FAILED:' + (e instanceof Error ? e.message : String(e)));
  }
  return undefined;
}

function ev(src, epoch, seqRef, kind, payload) {
  const e = Object.freeze({ epoch, seq: seqRef.n++, ts: Date.now(), src, kind, payload: Object.freeze({ ...(payload || {}) }) });
  return e;
}

async function sha256HexBrowser(u8) {
  if (globalThis.crypto && crypto.subtle) {
    const d = await crypto.subtle.digest('SHA-256', u8);
    return [...new Uint8Array(d)].map((b) => b.toString(16).padStart(2, '0')).join('');
  }
  throw new Error('IMAGE_HASH_MISMATCH:no-subtle-crypto');
}

export async function createAndroidRuntime(input) {
  const canvas = input && input.canvas;
  const onEvent = (input && input.onEvent) || (() => {});
  if (!canvas) throw new Error('RUNTIME_FACTORY_MISSING:no-canvas');
  let seqRef = { n: 0 };
  let epochRef = { n: 0 };
  let destroyed = false;

  function emit(kind, payload) {
    try { onEvent(ev('android-runtime', epochRef.n, seqRef, kind, payload)); } catch (_e) {}
  }

  async function probeG0(ctx) {
    // Browser parity with the CLI artifact gate: reject fixture media and
    // stub WASM here too. An 8-byte module that instantiates, or images
    // whose manifest admits fixtures, can never pass G0.
    try {
      if (!wasmInstance) return { status: 'BLOCKED', evidence: [], error: 'RUNTIME_NOT_BUILT' };
      if (!wasmMemoryInfo || wasmMemoryInfo.bytes < 1024) {
        return { status: 'BLOCKED', evidence: [], error: 'WASM_BOOTSTRAP_ONLY' };
      }
      if (!wasmMemoryInfo.exports || (!wasmMemoryInfo.exports.includes('initWasm') && !wasmMemoryInfo.exports.includes('createAndroidRuntime'))) {
        return { status: 'BLOCKED', evidence: [], error: 'WASM_NO_RUNTIME_EXPORTS' };
      }
      const mres = await fetch(new URL('../images/manifest.json', import.meta.url));
      if (!mres.ok) return { status: 'BLOCKED', evidence: [], error: 'IMAGE_ROLE_MISSING' };
      const manifest = await mres.json();
      if (!manifest || !manifest.androidVersion || !manifest.abi) {
        return { status: 'FAILED', evidence: [], error: 'IMAGE_ROLE_MISSING' };
      }
      const marker = JSON.stringify(manifest).toLowerCase();
      if (marker.includes('bootstrap-fixture') || (manifest.note || '').toLowerCase().includes('bootstrap')) {
        return { status: 'BLOCKED', evidence: [], error: 'BOOTSTRAP_FIXTURES' };
      }
      emit('asset_check', { manifest: manifest.androidVersion });
      return { status: 'PASSED', evidence: ['wasm-exports:' + wasmMemoryInfo.exports.join(','), 'manifest:' + manifest.androidVersion], error: null };
    } catch (e) {
      return { status: 'FAILED', evidence: [], error: 'ASSET_FETCH_FAILED' };
    }
  }

  async function probeG1(ctx) {
    // G1 passes ONLY on a live Android boot: the vendored v86 bundle is
    // attached through rt.attachV86({bundleUrl,...}) (never a raw Worker),
    // the REAL kernel/initrd are staged via rt.loadBoot(), BIOS+bundle boot
    // the guest, and serial output (>0B, kernel marker) plus a v86 pong are
    // observed. Anything less stays BLOCKED.
    let rt = null;
    try {
      const [{ VmRuntime }] = await Promise.all([import('../src/vm/vm_runtime.js')]);
      rt = new VmRuntime({ heartbeatIntervalMs: 1000, watchdogTimeoutMs: 30000 });
      await rt.create({ ramSize: 256 * 1024 * 1024 });
      // Stage the real boot assets over HTTP (same bytes the CLI pins).
      const [kres, ires] = await Promise.all([
        fetch(new URL('../images/kernel', import.meta.url)),
        fetch(new URL('../images/initrd.img', import.meta.url)),
      ]);
      if (!kres.ok || !ires.ok) return { status: 'BLOCKED', evidence: [], error: 'IMAGE_ROLE_MISSING' };
      const kernel = new Uint8Array(await kres.arrayBuffer());
      const initrd = new Uint8Array(await ires.arrayBuffer());
      await rt.loadBoot({ kernel, initrd, cmdline: 'console=ttyS0 root=/dev/ram0 rw' });
      let serialSeen = '';
      rt.onSerial((t) => { serialSeen += t; });
      // Attach through the fail-closed runtime path (validates {V86} shape,
      // boots bios+bzimage+initrd). Rejects V86_NOT_PRESENT when unvendored.
      // Budgets: bundle fetch + wasm compile + BIOS can take ~2 minutes.
      await rt.attachV86({
        bundleUrl: new URL('../vendor/v86/libv86.mjs', import.meta.url).href,
        wasmUrl: new URL('../vendor/v86/v86.wasm', import.meta.url).href,
        biosUrl: new URL('../vendor/v86/bios.bin', import.meta.url).href,
        bzimageUrl: new URL('../images/kernel', import.meta.url).href,
        initrdUrl: new URL('../images/initrd.img', import.meta.url).href,
        cmdline: 'console=ttyS0 root=/dev/ram0 rw',
        memorySize: 256 * 1024 * 1024,
        startTimeoutMs: 120000,
      }, { attachTimeoutMs: 150000 });
      await rt.start();
      // Wait for guest serial (worker forwards v86 serial0 as EVT_SERIAL_OUT).
      const deadline = Date.now() + 120000;
      while (Date.now() < deadline && !/Linux version/i.test(serialSeen)) {
        await new Promise((r) => setTimeout(r, 1000));
      }
      const pong = await new Promise((resolve) => {
        // Under guest load the worker answers between emulation slices;
        // retry the ping rather than mistaking a busy worker for a dead one.
        let tries = 0;
        const attempt = () => {
          tries += 1;
          const id = rt.sendWorkerMessage('CMD_PING', { seq: tries, hostTime: Date.now() });
          rt.pendingResolvers.set(id, (payload) => resolve(payload));
          setTimeout(() => {
            if (tries < 8) attempt();
            else resolve(null);
          }, 5000);
        };
        attempt();
      });
      const backend = pong && pong.backend;
      const stubQuanta = (pong && pong.stubQuanta) || 0;
      const serialOk = serialSeen.length > 0 && /Linux version|BIOS|SeaBIOS/i.test(serialSeen);
      await rt.destroy().catch(() => {});
      rt = null;
      if (backend !== 'v86' || stubQuanta > 0) {
        return { status: 'BLOCKED', evidence: [], error: 'V86_NOT_PRESENT' };
      }
      if (!serialOk) {
        return { status: 'BLOCKED', evidence: ['serial:' + serialSeen.length + 'B'], error: 'ANDROID_BOOT_TIMEOUT' };
      }
      emit('vm_create', { backend: 'v86' });
      emit('boot_start', { serial: serialSeen.slice(0, 128) });
      emit('kernel_seen', { serial: serialSeen.length });
      return { status: 'PASSED', evidence: ['v86-live-boot', 'backend:v86', 'serial:' + serialSeen.length + 'B'], error: null };
    } catch (e) {
      try { if (rt) await rt.destroy().catch(() => {}); } catch (_e2) {}
      const msg = e instanceof Error ? e.message : String(e);
      if (/V86_NOT_PRESENT|V86_API_INCOMPATIBLE/.test(msg)) return { status: 'BLOCKED', evidence: [], error: 'V86_NOT_PRESENT' };
      return { status: 'FAILED', evidence: [], error: msg.slice(0, 120) };
    }
  }

  async function probeG2(ctx) {
    try {
      const [{ GuestMem }, { PciBus }, { Virtqueue }] = await Promise.all([
        import('../src/vm/guest_mem.js'),
        import('../src/virtio/pci_bus.js'),
        import('../src/virtio/virtqueue.js'),
      ]);
      const mem = new GuestMem(4096);
      mem.writeU32(100, 0x12345678);
      if (mem.readU32(100) !== 0x12345678) throw new Error('GUEST_RAM_SELFTEST');
      let rejected = false;
      try { mem.readU32(4093); } catch (_e) { rejected = true; }
      if (!rejected) throw new Error('BOUNDS_NOT_ENFORCED');
      const vq = new Virtqueue(0, 8);
      if (typeof vq.shouldNotify !== 'function') throw new Error('VIRTQUEUE_CONTRACT');
      return { status: 'PASSED', evidence: ['guestmem-bounds-ok', 'virtqueue-contract-ok'], error: null };
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      return { status: 'FAILED', evidence: [], error: msg };
    }
  }

  async function probeG3(ctx) {
    try {
      const mres = await fetch(new URL('../images/manifest.json', import.meta.url));
      if (!mres.ok) return { status: 'BLOCKED', evidence: [], error: 'IMAGE_ROLE_MISSING' };
      const manifest = await mres.json();
      const roles = ['kernel', 'initrd.img', 'system.img', 'vendor.img', 'product.img'];
      const evidence = [];
      const hashes = manifest.sha256 || {};
      const images = manifest.images || {};
      for (const role of roles) {
        const file = (images[role] && images[role].file) || (role === 'kernel' ? 'kernel' : role);
        const ires = await fetch(new URL('../images/' + file, import.meta.url));
        if (!ires.ok) return { status: 'BLOCKED', evidence, error: 'IMAGE_ROLE_MISSING:' + role };
        const bytes = new Uint8Array(await ires.arrayBuffer());
        const wantSize = images[role] && images[role].size;
        if (wantSize !== undefined && bytes.byteLength !== Number(wantSize)) {
          return { status: 'FAILED', evidence, error: 'IMAGE_SIZE_MISMATCH:' + role };
        }
        const wantHash = hashes[role] || (images[role] && images[role].sha256);
        if (wantHash) {
          const actual = await sha256HexBrowser(bytes);
          if (actual !== String(wantHash).toLowerCase()) {
            return { status: 'FAILED', evidence, error: 'IMAGE_HASH_MISMATCH:' + role };
          }
        }
        evidence.push(role + ':' + bytes.byteLength + 'B-verified');
      }
      // Provenance: every role must be pinned authentic release media, and the
      // manifest must not admit fixtures. Hash/size match alone is not enough.
      const marker = JSON.stringify(manifest).toLowerCase();
      if (marker.includes('bootstrap-fixture') || (manifest.note || '').toLowerCase().includes('bootstrap')) {
        return { status: 'BLOCKED', evidence, error: 'BOOTSTRAP_FIXTURES' };
      }
      for (const role of roles) {
        if (!images[role] || !images[role].authentic) {
          return { status: 'BLOCKED', evidence, error: 'IMAGE_UNPROVENANCED:' + role };
        }
      }
      emit('disk_commit', { roles: roles.length });
      return { status: 'PASSED', evidence, error: null };
    } catch (e) {
      return { status: 'BLOCKED', evidence: [], error: 'IMAGE_ROLE_MISSING' };
    }
  }

  async function probeBlocked(code) {
    return { status: 'BLOCKED', evidence: [], error: code };
  }

  const runtime = {
    async runValidationLoop(input2) {
      if (destroyed) throw new Error('VALIDATION_RESULT_INVALID:destroyed');
      const runId = input2 && input2.runId;
      const epoch = input2 && input2.epoch;
      const onGate = input2 && input2.onGate;
      if (typeof runId !== 'string' || !runId) throw new Error('VALIDATION_RESULT_INVALID');
      if (typeof epoch !== 'number') throw new Error('VALIDATION_RESULT_INVALID');
      epochRef.n = epoch;
      const probes = {
        g0: probeG0,
        g1: probeG1,
        g2: probeG2,
        g3: probeG3,
        g4: () => probeBlocked('VM_NOT_RUNNING'),
        g5: () => probeBlocked('AUDIO_BLOCKED'),
        g6: () => probeBlocked('GPU_PROTOCOL_UNSUPPORTED'),
        g7: () => probeBlocked('ANDROID_BOOT_TIMEOUT'),
        g8: () => probeBlocked('EGL_UNSUPPORTED'),
        g9: () => probeBlocked('GPU_DEVICE_LOST:unproven'),
      };
      const result = await runValidationGates({ runId, epoch, probes, onGate });
      try { onEvent(ev('android-runtime', epoch, seqRef, result.ready ? 'android_ready' : 'fatal_error', { runId, ready: result.ready })); } catch (_e) {}
      return result;
    },
    async destroy() {
      destroyed = true;
      wasmInstance = null;
    },
  };
  return runtime;
}

export const __CONTRACT__ = Object.freeze({ gates: GATE_IDS });
